# Generated by Django 3.2.4 on 2021-06-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telegram_sub', models.BooleanField(default=False)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
