# Generated by Django 3.2.4 on 2021-06-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotform', '0002_alter_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
