# Generated by Django 3.2.4 on 2021-06-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotform', '0003_alter_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
