# Generated by Django 3.2.4 on 2021-06-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotform', '0004_alter_user_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='time',
            new_name='created_at',
        ),
    ]
