# Generated by Django 3.2.4 on 2021-06-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotform', '0005_rename_time_user_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
