# Generated by Django 3.2.4 on 2021-06-12 09:33

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slotform', '0006_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('state_id', models.IntegerField()),
                ('state_name', models.TextField()),
            ],
            options={
                'db_table': 'states',
            },
        ),
    ]
