# Generated by Django 3.2.4 on 2021-06-12 09:46

from django.db import migrations, models
import djongo.models.fields
import slotform.models


class Migration(migrations.Migration):

    dependencies = [
        ('slotform', '0007_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('is_telegram', models.BooleanField()),
                ('district_id', models.IntegerField()),
                ('district_name', models.TextField()),
                ('state_id', djongo.models.fields.EmbeddedField(model_container=slotform.models.state)),
            ],
            options={
                'db_table': 'districts',
            },
        ),
    ]
