# Generated by Django 3.2.4 on 2021-06-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotform', '0008_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='state',
        ),
    ]
