# Generated by Django 3.2.4 on 2021-06-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slotform', '0010_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slotform.state'),
        ),
    ]
