# Generated by Django 3.2.4 on 2021-06-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotform', '0011_alter_district_state_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='state_id',
        ),
    ]
