# Generated by Django 3.2.4 on 2021-06-12 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slotform', '0012_remove_district_state_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='state_id',
            field=models.ForeignObject(default=django.utils.timezone.now, from_fields=['state_id'], on_delete=django.db.models.deletion.CASCADE, to='slotform.state', to_fields=['_id']),
            preserve_default=False,
        ),
    ]
