# Generated by Django 3.2.4 on 2021-06-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slotform', '0013_district_state_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='state_id',
            field=models.ForeignObject(from_fields=('_id',), on_delete=django.db.models.deletion.CASCADE, to='slotform.state', to_fields=('state_id',)),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_id',
            field=models.IntegerField(unique=True),
        ),
    ]
