# Generated by Django 3.2.4 on 2021-06-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slotform', '0014_auto_20210612_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='state_id',
            field=models.ForeignObject(from_fields=('state_id',), on_delete=django.db.models.deletion.CASCADE, to='slotform.state', to_fields=('_id',)),
        ),
    ]
