# Generated by Django 3.2.4 on 2021-06-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotform', '0016_remove_district_state_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='telegram_channel_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='district',
            name='telegram_channel_name',
            field=models.TextField(default=''),
        ),
    ]
